import type { Metadata } from "next";

import "./globals.css";
import Header from './components/Header'
export const metadata: Metadata = {
  title: "Grocery Application Next js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en">
      <body >
        <Header/>
        {children}</body>
    </html>
  );
}
