import type { Metadata } from "next";
import ApiContext from './contex/ApiContex'
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer"
export const metadata: Metadata = {
  title: "Grocery Application Next js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <ApiContext>
          <Header />
          {children}
          <Footer/>
     </ApiContext>
      </body>
    </html>
  );
}